# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.1.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
springBoot = "3.4.1"
springDependencyManagement = "1.1.7"
kafka = "3.9.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Spring Boot
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }

# database
mysql-jdbcDriver = { module = "com.mysql:mysql-connector-j" }
mysql-r2dbcDriver = { module = "dev.miku:r2dbc-mysql" }
springBootStarterData-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
springBootStarterData-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
springBootStarterData-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }

# Kafka
springKafka = { module = "org.springframework.kafka:spring-kafka" }
kafkaClients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
springBootCommon = ["springBootStarterWeb", "springBootStarterValidation", "springBootStarterActuator"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinPluginSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }