spring:
  application:
    name: service-auth
  
  profiles:
    active: local

  flyway:
    locations: classpath:database/migration

  main:
    web-application-type: servlet

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: ${app.swagger.gateway-prefix}/v3/api-docs/swagger-config
    url: ${app.swagger.gateway-prefix}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  swagger:
    enabled: true
    gateway-prefix: /auth
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
    private-key: ${JWT_PRIVATE_KEY}
    issuer: ${JWT_ISSUER}
    access-expire-seconds: ${JWT_ACCESS_SECONDS}
    refresh-expire-seconds: ${JWT_REFRESH_SECONDS}
