spring:
  application:
    name: service-user
  
  profiles:
    active: local

  flyway:
    locations: classpath:database/migration

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: ${app.swagger.gateway-prefix}/v3/api-docs/swagger-config
    url: ${app.swagger.gateway-prefix}/v3/api-docs

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  swagger:
    enabled: true
    gateway-prefix: /user
